#General IO
#ATTENTION: use absolute paths
##Input
inDir="/Users/thisUserName/lvi/toReplicateExperiments/rawReads/" #path to rawReads directory containing the raw count data
scriptsDir="/Users/thisUserName/lviProjectDNAScripts/" #path to lviProjectDNAScripts
originalSampleDataFile="/Users/thisUserName/lvi/toReplicateExperiments/designFile.csv" #path to csv design file

#Output
acnaDir="/Users/thisUserName/lvi/acna/" #path to the output directory for CNA variant calls
breakpointDir="/Users/thisUserName/lvi/breakpoints/" #path to the output directory for breakpoint calls
plotDir="/Users/thisUserName/lvi/plots/" #path to the output directory for plots
sampleDataFile="/Users/thisUserName/lvi/sampleDataFile.csv" #path to the CSV design file that is generated by CNAcalling.R and used by all downstream analyses

#Other general configuration variables
mc_cores=1 #number of CPU cores you want to use in parallel for some of the analyses

#Genetics
summaryFileName="dataForGenetics.rds" #filename to re-use pre-generated data. By default, it will be generated or expected in $acnaDir

#GISTIC
gisticInputFile="/Users/thisUserName/lvi/gistic/allInput.in" #path to the input file for GISTIC2.0, which will be generated by makeGisticInputFromTsvFiles.sh
gisticOutDir="/Users/thisUserName/lvi/gistic/allOutput/" #path to the output directory for GISTIC2.0
gisticMatrixFile="/Users/thisUserName/apps/gistic2/refgenefiles/hg38.UCSC.add_miR.160920.refgene.mat" #path to the refgene matrix distributed with GISTIC2.0: hg38.UCSC.add_miR.160920.refgene.mat
##Alternative analysis
gisticLVIInputFile="/Users/thisUserName/lvi/gistic/LVIInput.in" #path to the alternative input file for GISTIC2.0, generated by lviSelection after running makeGisticInputFromTsvFiles.
gisticLVIOutDir="/Users/thisUserName/lvi/gistic/LVIOutput/" #path to the output directory of the alternative GISTIC2.0 analysis

#runPhylip
phylipDir="/Applications/phylip/" #path to Phylip's programs
phylipSuffix=".app/Contents/MacOS/" #suffix to add to the program name to find the executable (e.g. $phylipDir/dollop${phylipSuffix}/dollop should point to the dollop executable): MacOS default

#gisticAssociations and deNovoEnrichmentGistic 
gisticLVIOnly=F #logical indicating if the deNovoEnrichmentGistic must be executed with the lvi-only recurrent alterations or all. This does not affect gisticAssociations, which is always done with the results using all input data for GISTIC2.0
gisticOutputFilename="all_lesions.conf_90.txt" #doesn't needed to be changed

#diffExpVsCNAs
##Input
diffExpDir="/Users/thisUserName/lvi/toReplicateExperiments/diffExpGenes/" #path to the directory with files with differentially expressed genes (names below, not need to be changed)
diffExpStageDisc="diffExpStageDisc.xlsx" 
diffExpStageVal="diffExpStageVal.xlsx"
diffExpAcrossDisc="diffExpAcrossDisc.csv"
diffExpAcrossVal="diffExpAcrossVal.csv"
diffExpIBCLVIDiscID="diffExpIBCLVIDiscID.xlsx"
diffExpIBCLVIDiscNID="diffExpIBCLVIDiscNID.xlsx"
diffExpIBCLVIValID="diffExpIBCLVIValID.csv"
diffExpIBCLVIValNID="diffExpIBCLVIValNID.csv"

#clonalityScore
inputDataImageName="clonalityInputData.RData" #filename to re-use pre-generated data. It will be generated or expected in acnaDir
calculationDataImageName="clonalityDistributionData.RData" #filename to re-use pre-generated data. It will be generated or expected in acnaDir
